### ISSUE TITLE
memcache-transcoders lib missing

### ISSUE THREAD

**Issue by ipince** [yubin154/memcache_transcoder#1]
Hi,

I'm unable to find this dependency as indicated in the README.

```
<dependency>
  <groupId>com.google.appengine</groupId>
  <artifactId>memcache-transcoders</artifactId>
  <version>1.0-SNAPSHOT</version>
</dependency>
```

Where can that be found?  Thanks!

**Comment by yubin154** [comment]
You can run the following commands to build this dependency locally

git clone https://github.com/yubin154/memcache_transcoder
cd memcache_transcoder
mvn clean install

**Comment by ipince** [comment]
Thank you, this works :)
